### ISSUE TITLE
Consistent crashing

### ISSUE THREAD

**Issue by hubmaster0** [Viceroyy/Fusion#12]
Windows ver.: Windows 10 Home 22H2

Fusion build: Aug 9, 2024, 20:35:58

Both general and visual configs:

https://file.io/c1eVI6LckdIt
https://file.io/uEmMsRQx9WD4

I've relaunched the game 5 times, just from crashing. I can't seem to find what causes it, but it's only when I'm in game.

**Comment by whohyno** [comment]
No minidumps created on the desktop? And did this start happening after newest commit?

**Comment by hubmaster0** [comment]
Correct. I didn't get any dump files after the crashes. And yes

**Comment by Viceroyy** [comment]
I just pushed an update, could you test and see if it still happens?

**Comment by hubmaster0** [comment]
I just loaded up a game in 2fort and it took about 3 minutes for a crash to happen, same configs I used before, using the newest build. I still didn't get any dump files either.

**Comment by whohyno** [comment]
When doe sit crash, just randomly, or when you do an action or something happens on the map?
Did you try using default config aswell?

**Comment by hubmaster0** [comment]
The crashes are random, yea. I've used the default config as well, didn't even mess with the settings and I still crashed.
