### ISSUE TITLE
Problems that i know

### ISSUE THREAD

**Issue by barankurtulus-html** [Viceroyy/Fusion#13]
Windows 10 22H2

i've forked the latest one.

Randomly crashing while a spy decloaking. No minidmps or anything. I've implemented autovaccinator so i thought that might be the problem but no. Also without backtracking enabled (and enabled also i guess) aimbot targets the old ticks and misses everything. latest fake latency update caused auto backstabbing to not work. Melee swing prediction also misses. doubletapping doesnt work after latest updates (after amalgam) That is everything i know.

**Comment by sp00kY0** [comment]
My opinion: skill issue
