### ISSUE TITLE
fix passive dt recharge

### ISSUE THREAD

**Issue by Gergish001** [Viceroyy/Fusion#15]
when you enable passive recharge it works good, but after load on another game passive recharge stop working

https://github.com/user-attachments/assets/79ec9f2b-4112-4fb1-9c5e-21c6a0baa324

**Comment by canedoly** [comment]
its caused when the last server's tickcount is larger then our current server, it can be fixed by making iPassiveTick a member of TickHandler and setting it to 0 in Reset()

**Comment by rei-2** [comment]
the goal was always to recharge x ticks per second rather than how it works now, though i hadn't gotten around to reworking it until now after becoming aware of this bug. i decided to rework it in a way that didn't need any member variables
```
static float flPassiveTime = 0.f;
flPassiveTime = std::max(flPassiveTime - TICK_INTERVAL, -TICK_INTERVAL);
if (Vars::CL_Move::Doubletap::PassiveRecharge.Value && 0.f >= flPassiveTime)
{
	bPassive = true;
	flPassiveTime += 1.f / Vars::CL_Move::Doubletap::PassiveRecharge.Value;
}
```

**Comment by Gergish001** [comment]
man you are hero
