### ISSUE TITLE
so is it crashing for a lot of people or no?

### ISSUE THREAD

**Issue by 1fbw** [Viceroyy/Fusion#16]
i need info if i should use it. also whats that chance of me getting vac banned. i already got 3 vac bans for using alagman or whatever it was. i dont wanna waste another 40$ just to get my taunts back

**Comment by Viceroyy** [comment]
use vac bypass by daniel and at that point just get a paid cheat to avoid bans and wasted money

**Comment by 1fbw** [comment]
i would get lmaobox if i would get paid cheats, but thats why im here

**Comment by 1fbw** [comment]
im broke

**Comment by 1fbw** [comment]
also @Viceroyy does TFGhost work too? thats what i used the last few times

**Comment by Viceroyy** [comment]
> i would get lmaobox if i would get paid cheats, but thats why im here

its 2024 ideally you should either be getting rijin or moneybot anyway

> also @Viceroyy does TFGhost work too? thats what i used the last few times

idk i never used it, i recommend using xenos instead

**Comment by 1fbw** [comment]
alr thanks. ill try xenos out

**Comment by gamergod69299** [comment]
yeah it is kinda crashing... do you have a fix?

**Comment by 1fbw** [comment]
idk, haven't tried it yet lmao
