### ISSUE TITLE
32 bit version

### ISSUE THREAD

**Issue by V-Rusa** [Viceroyy/Fusion#18]
Make the 32bit version:)

**Comment by Viceroyy** [comment]
I would prefer to create a Linux version over a 32-bit version, though neither is likely to happen

**Comment by acapro200** [comment]
theres already fware if u want 32bit version or somehing soo yehhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by Gergish001** [comment]
> I would prefer to create a Linux version over a 32-bit version, though neither is likely to happen

if you do that i instantly going to install linux instead of windows
