### ISSUE TITLE
Debug settings for projectile

### ISSUE THREAD

**Issue by Gergish001** [Viceroyy/Fusion#28]
I knew that fusion has the "advanced" settings to configure projectile when enabling debug mode, but after i delete nosave from vars.h to them i still cant save the debug settings, 
What can i do with that?

**Comment by canedoly** [comment]
> I knew that fusion has the "advanced" settings to configure projectile when enabling debug mode, but after i delete nosave from vars.h to them i still cant save the debug settings, 
> What can i do with that?

skill issue

**Comment by Gergish001** [comment]
> > I knew that fusion has the "advanced" settings to configure projectile when enabling debug mode, but after i delete nosave from vars.h to them i still cant save the debug settings,
> > What can i do with that?
> 
> skill issue

☹
