### ISSUE TITLE
Medigun Particles don't update real time

### ISSUE THREAD

**Issue by whohyno** [Viceroyy/Fusion#8]
You have to change to another weapon and back to medigun to see the new effect.

**Comment by Viceroyy** [comment]
I don't know if this is fixable, maybe cl_fullupdate when changing effects could work

**Comment by canedoly** [comment]
> I don't know if this is fixable, maybe cl_fullupdate when changing effects could work

I do this in FSN:
```
static std::string OldMedigunBeam = {};
static std::string OldMedigunCharged = {};
if ( OldMedigunBeam != Vars::Visuals::Medigun::MedigunBeam.Value || OldMedigunCharged != Vars::Visuals::Medigun::MedigunCharged.Value ) {
	auto pLocal = H::Entities.GetLocal( );
	auto pWeapon = H::Entities.GetWeapon( );
	if ( pLocal && pWeapon && pWeapon->m_iWeaponID( ) == TF_WEAPON_MEDIGUN ) {
		static auto manage = S::ManageChargeEffectFunc.As< void( __thiscall* )( void*, bool )>( );
		static auto update = S::UpdateEffectFunc.As< void( __thiscall* )( void* )>( );
		static auto stop = S::StopChargeEffectFunc.As< void( __thiscall* )( void* )>( );

		update( pWeapon );
		stop( pWeapon );
		manage( pWeapon, false );
	}
	OldMedigunBeam = Vars::Visuals::Medigun::MedigunBeam.Value;
	OldMedigunCharged = Vars::Visuals::Medigun::MedigunCharged.Value;
}
```

**Comment by whohyno** [comment]
> I don't know if this is fixable, maybe cl_fullupdate when changing effects could work
It works for the Charge particle, but Beam just doesn't draw it until you change weapons
> I do this in FSN:
Nice

**Comment by whohyno** [comment]
> I don't know if this is fixable, maybe cl_fullupdate when changing effects could work

It works for the Charge particle, but Beam just causes it to not draw

**Comment by rei-2** [comment]
> I don't know if this is fixable, maybe cl_fullupdate when changing effects could work

i'd recommend against cl_fullupdate, mainly due to the fact that this resets weapon crit data and there currently are not any safeguards in place to restore them as they were

**Comment by IamIndeedGamingAsHardAsICan03489** [comment]
mad? here
this is simple enough to fix
after original FSN call, you can update the effects
`if ( OldMedigunEffect != Config->Visuals->MedigunBeamEffect || OldMedigunChargeEffect != Config->Visuals->MedigunChargeEffect )
{
	if ( LocalPlayer && LocalWeapon && LocalWeapon->WeaponID() == TF_WEAPON_MEDIGUN )
	{
		// update all effects
		( ( void( __thiscall* )( void* ) ) Globals->Addresses->WeaponMedigun__UpdateEffects )( LocalWeapon );

		( ( void( __thiscall* )( void* ) ) Globals->Addresses->WeaponMedigun__StopChargeEffect )( LocalWeapon );
		( ( void( __thiscall* )( void*, bool ) ) Globals->Addresses->WeaponMedigun__ManageChargeEffect )( LocalWeapon, false );
		
	}

	OldMedigunEffect = Config->Visuals->MedigunBeamEffect;
	OldMedigunChargeEffect = Config->Visuals->MedigunChargeEffect;
}`

**Comment by canedoly** [comment]
> edit: idk why the beam would disappear but it works just fine for me

lagging out or using cl_fullupdate when healing causes the beam to disappear is a tf2 bug
