### ISSUE TITLE
Applying fonts causes DPI to go back to 1.0

### ISSUE THREAD

**Issue by whohyno** [Viceroyy/Fusion#9]
Another small issue.
Important to mention this doesn't reset the window's DPI, only the text/fonts inside them.

**Comment by Viceroyy** [comment]
argh this font stuff will be the end of me

**Comment by whohyno** [comment]
Fixed by:
Fonts.h
`void Reload(float flDPI = 1.f);` TO 
`void Reload();`

Fonts.cpp
`void CFonts::Reload(float flDPI)` TO
`void CFonts::Reload()`
and switching all flDPI parameters to `Vars::Menu::DPI.Value`

Menu.cpp Line 851
`H::Fonts.Reload(Vars::Menu::DPI.Map["default"]);` to
`H::Fonts.Reload();`

**Comment by RileyKun** [comment]
> Fixed by: Fonts.h `void Reload(float flDPI = 1.f);` TO `void Reload();`
> 
> Fonts.cpp `void CFonts::Reload(float flDPI)` TO `void CFonts::Reload()` and switching all flDPI parameters to `Vars::Menu::DPI.Value`
> 
> Menu.cpp Line 851 `H::Fonts.Reload(Vars::Menu::DPI.Map["default"]);` to `H::Fonts.Reload();`

Why strip DPI completely instead of actually fixing the issue at hand?

**Comment by whohyno** [comment]
> Why strip DPI completely instead of actually fixing the issue at hand?

Not stripping it, just changing the flDPI to DPI.Value, doesn't get changed immediately though and creates a new issue

**Comment by whohyno** [comment]
The issue gets solved with no further repercussions on Line 882 in Menu.cpp
`H::Fonts.Reload();` to
`H::Fonts.Reload(Vars::Menu::DPI.Map["default"]);`
